name: remote ssh command

on:
  push:
    branches:
      - main  # Replace with your preferred branch

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node.js environment with NVM
      run: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
      shell: bash

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/html/
          
          # Install Node Version Manager (NVM)
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
          source ~/.bashrc

          # Use NVM to install and switch to Node.js v18.17.1
          nvm install v18.17.1
          nvm use v18.17.1

          # Verify Node.js and npm versions
          node -v
          npm -v
